blog/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', Posts.as_view(), name='blog'),
    path('post/create/', PostCreate.as_view(), name='post_create'),
    path('post/<str:slug>/update/', PostUpdate.as_view(), name='post_update'),
    path('post/<str:slug>/delete/', PostDelete.as_view(), name='post_delete'),
    path('post/<str:slug>/', PostDetail.as_view(), name='post_detail'),
    path('tags/', TagsList.as_view(), name='tags_list'),
    path('tag/create/', TagCreate.as_view(), name='tag_create'),
    path('tag/<str:slug>/update/', TagUpdate.as_view(), name='tag_update'),
    path('tag/<str:slug>/delete/', TagDelete.as_view(), name='tag_delete'),
    path('tag/<str:slug>/', TagDetail.as_view(), name='tag_detail')
]

website/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import *

urlpatterns = [
    path('', redirect_blog),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls'))
]

blog/models.py
from django.db import models
from django.shortcuts import reverse
from django.utils.text import slugify

from time import time


def gen_slug(s):
    new_slug = slugify(s, allow_unicode=True)
    return new_slug + '-' + str(int(time()))


class Post(models.Model):
    title = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, blank=True, unique=True)
    body = models.TextField(blank=True, db_index=True)
    tags = models.ManyToManyField('Tag', blank=True, related_name='posts')
    date_pub = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"
        ordering = ['-date_pub']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('post_update', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('post_delete', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = gen_slug(self.title)
        super(Post, self).save(*args, **kwargs)


class Tag(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True)

    class Meta:
        verbose_name = 'Тэг'
        verbose_name_plural = 'Тэги'
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('tag_detail', kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('tag_update', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('tag_delete', kwargs={'slug': self.slug})

blog/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import *


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['title', 'slug']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'slug': forms.TextInput(attrs={'class': 'form-control'})
        }

    def clean_slug(self):
        new_slug = self.cleaned_data['slug'].lower()
        if new_slug == 'create':
            raise ValidationError('Slug не может быть словом "create".')
        return new_slug


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'slug', 'body', 'tags']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'slug': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'tags': forms.SelectMultiple(attrs={'class': 'form-control'}),
        }

    def clean_slug(self):
        new_slug = self.cleaned_data['slug'].lower()
        if new_slug == 'create':
            raise ValidationError('Slug не может быть словом "create".')
        return new_slug

blog/views.py
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q

from .models import *
from .forms import TagForm, PostForm


class Posts(generic.ListView):
    template_name = 'blog/blog.html'
    model = Post
    paginate_by = 2
    flag = False

    def get_queryset(self):
        queryset = super(Posts, self).get_queryset()
        self.q = self.request.GET.get("q")
        if self.q:
            self.flag = True
            return queryset.filter(Q(title__icontains=self.q) | Q(body__icontains=self.q))
        return queryset


class PostDetail(generic.DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = {'admin_object': self.object, 'detail': True}
        context.update(kwargs)
        return super().get_context_data(**context)


class PostCreate(LoginRequiredMixin, generic.CreateView):
    form_class = PostForm
    template_name = 'blog/post_create.html'
    raise_exception = True


class PostUpdate(LoginRequiredMixin, generic.UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/post_update.html'
    raise_exception = True


class PostDelete(LoginRequiredMixin, generic.DeleteView):
    model = Post
    success_url = reverse_lazy('blog')
    template_name = 'blog/post_delete.html'
    raise_exception = True


class TagsList(generic.ListView):
    template_name = 'blog/tags_list.html'
    model = Tag


class TagDetail(generic.DetailView):
    model = Tag

    def get_context_data(self, **kwargs):
        context = {'admin_object': self.object, 'detail': True}
        context.update(kwargs)
        return super().get_context_data(**context)


class TagCreate(LoginRequiredMixin, generic.CreateView):
    form_class = TagForm
    template_name = 'blog/tag_create.html'
    raise_exception = True


class TagUpdate(LoginRequiredMixin, generic.UpdateView):
    model = Tag
    form_class = TagForm
    template_name = 'blog/tag_update.html'
    raise_exception = True


class TagDelete(LoginRequiredMixin, generic.DeleteView):
    model = Tag
    success_url = reverse_lazy('tags_list')
    template_name = 'blog/tag_delete.html'
    raise_exception = True

website/views.py
from django.shortcuts import redirect


def redirect_blog(request):
    return redirect('blog', permanent=True)

blog/templates/blog/blog.html
{% extends 'blog/blog_base.html' %}
{% block title %}
    {{ block.super }} - List
{% endblock %}
{% block content %}
    {% if request.GET.q  %}
        <h1 class="mb-5">Страница поиска:</h1>
    {% else %}
        <h1 class="mb-5">Посты:</h1>
    {% endif %}
    {% for post in post_list %}
        {% include 'blog/includes/post_card_template.html' %}
    {% endfor %}
{% endblock %}

blog/templates/blog/blog_base.html
{% extends 'base.html' %}
{% block admin-panel %}
    <div class="btn-group">
      <button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Создать
      </button>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="{% url 'post_create' %}">Пост</a>
        <a class="dropdown-item" href="{% url 'tag_create' %}">Тэг</a>
      </div>
    </div>
    <a href="{{ admin_object.get_update_url }}" class="btn btn-light edit" style="{% if detail %}display: block;{% endif %}">Редактировать</a>
    <a href="{{ admin_object.get_delete_url }}" class="btn btn-danger delete" style="{% if detail %}display: block;{% endif %}">Удалить</a>
{% endblock %}

blog/templates/blog/includes/post_card_template.html
<div class="card mt-3">
    <div class="card-header">
        {{ post.date_pub }}
    </div>
    <div class="card-body">
        <h5 class="card-title">{{ post.title }}</h5>
        <p class="card-text">{{ post.body|truncatechars:15 }}</p>
        <a href="{{ post.get_absolute_url }}" class="btn btn-light">Read</a>
    </div>
    <div class="card-footer text-muted">
        Tags:
        {% for tag in post.tags.all %}
            <a href="{{ tag.get_absolute_url }}">{{ tag.title }}</a>
        {% endfor %}
    </div>
</div>

blog/templates/blog/post_create.html
{% extends 'blog/blog_base.html' %}
{% block title %}
    {{ block.super }} - Post Create
{% endblock %}
{% block content %}
    <form action="{% url 'post_create' %}" method="post">
        {% csrf_token %}
        {% for filed in form %}
            {% if filed.errors %}
                <div class="alert alert-danger mt-2">
                    {{ filed.errors }}
                </div>
            {% endif %}
            <div class="mt-2">
                {{ filed.label }}
                {{ filed }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary mt-3">Create Post</button>
    </form>
{% endblock %}

blog/templates/blog/post_delete.html
{% extends 'blog/blog_base.html' %}
{% block title %}
    Delete Post - {{ post.title }}
{% endblock %}
{% block content %}
    <form action="{{ post.get_delete_url }}" method="post">
        {% csrf_token %}
        <h3>Вы уверены, что хотите удалить пост?<b>{{ post.title|title }}</b></h3>
        <a href="{{ post.get_absolute_url }}">Нет</a>
        <button type="submit" name="button" class="btn btn-danger">Да</button>
    </form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/blog_base.html' %}
{% block title %}
    {{ post.title }} - {{ block.super }}
{% endblock %}
{% block content %}
    <h1 class="mt-5">
        {{ post.title }}
    </h1>
    <p>
        {{ post.body }}
    </p>
{% endblock %}

blog/templates/blog/post_update.html
{% extends 'blog/blog_base.html' %}
{% block title %}
    {{ block.super }} - Post Update
{% endblock %}
{% block content %}
    <form action="{{ post.get_update_url }}" method="post">
        {% csrf_token %}
        {% for filed in form %}
            {% if filed.errors %}
                <div class="alert alert-danger mt-2">
                    {{ filed.errors }}
                </div>
            {% endif %}
            {{ filed.label }}
            {{ filed }}
        {% endfor %}
        <button type="submit" class="btn btn-primary mt-2">Сохранить</button>
    </form>
{% endblock %}

blog/templates/blog/tag_create.html
{% extends 'blog/blog_base.html' %}
{% block title %}
    {{ block.super }}
{% endblock %}
{% block content %}
    <form action="{% url 'tag_create' %}" method="post">
        {% csrf_token %}
        {% for filed in form %}
            {% if filed.errors %}
                <div class="alert alert-danger mt-2">
                    {{ filed.errors }}
                </div>
            {% endif %}
            {{ filed.label }}
            {{ filed }}
        {% endfor %}
        <button type="submit" class="btn btn-primary mt-2">Create Tag</button>
    </form>
{% endblock %}

blog/templates/blog/tag_delete.html
{% extends 'blog/blog_base.html' %}
{% block title %}
    Delete Tag - {{ tag.title }}
{% endblock %}
{% block content %}
    <form action="{{ tag.get_delete_url }}" method="post">
        {% csrf_token %}
        <h3>Вы уверены, что хотите удалить тэг?<b>{{ tag.title|title }}</b></h3>
        <a href="{{ tag.get_absolute_url }}">Нет</a>
        <button type="submit" name="button" class="btn btn-danger">Да</button>
    </form>
{% endblock %}

blog/templates/blog/tag_detail.html
{% extends 'blog/blog_base.html' %}
{% block title %}
    Tag - {{ tag.title }}
{% endblock %}
{% block content %}
    <h1 class="mb-5">Post with "{{ tag.title|title }}" tag:</h1>
    {% for post in tag.posts.all %}
        {% include 'blog/includes/post_card_template.html' %}
    {% endfor %}
{% endblock %}

blog/templates/blog/tag_update.html
{% extends 'blog/blog_base.html' %}
{% block title %}
    {{ block.super }} - Tag Update
{% endblock %}
{% block content %}
    <form action="{{ tag.get_update_url }}" method="post">
        {% csrf_token %}
        {% for filed in form %}
            {% if filed.errors %}
                <div class="alert alert-danger mt-2">
                    {{ filed.errors }}
                </div>
            {% endif %}
            {{ filed.label }}
            {{ filed }}
        {% endfor %}
        <button type="submit" class="btn btn-primary mt-2">Сохранить</button>
    </form>
{% endblock %}

blog/templates/blog/tags_list.html
{% extends 'blog/blog_base.html' %}
{% block title %}
    {{ block.super }} - Tags list
{% endblock %}
{% block content %}
    <h1 class="mb-5">Tags:</h1>
    {% for tag in tag_list %}
        <h3><a href="{{ tag.get_absolute_url }}">{{ tag.title }}</a></h3>
    {% endfor %}
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>
    <title>
        {% block title %}Blog{% endblock %}
    </title>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'blog' %}">Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'tags_list' %}">Tags <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Temp_1</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Temp_2</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="{% url "blog" %}" method="GET">
                <input class="form-control mr-sm-2" type="text" placeholder="Для поиска..." aria-label="Search"
                       name="q">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
            </form>
        </div>
    </nav>
</header>
<main>
    <section>
        <div class="container mt-5">
            <div class="row">
                <div class="col-6 offset-md-2">
                    {% block content %}{% endblock %}
                    {% if page_obj.has_other_pages %}
                        <nav aria-label="..." class="mt-3">
                            <ul class="pagination">
                                {% if  page_obj.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link Next" href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"
                                           tabindex="-1">Пред.</a>
                                    </li>
                                {% endif %}
                                {% for n in page_obj.paginator.page_range %}
                                    <li class="page-item {% if n == page_obj.number %}active{% endif %}"
                                        aria-current="page">
                                        <a class="page-link" href='?page={{ n }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}'>{{ n }}<span
                                                class="sr-only">(current)</span></a>
                                    </li>
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a class="page-link Next" href="?page={{ page_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"
                                           tabindex="-1">След</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    {% endif %}
                </div>
            </div>
        </div>
        {% if request.user.is_authenticated and request.user.is_staff %}
            <div class="admin-panel align-items-center">
                <a href="/admin" class="btn btn-outline-info">Admin</a>
                {% block admin-panel %}{% endblock %}
            </div>
        {% endif %}
    </section>
</main>
{#<aside>#}
{#    Боковая колонка (сайдбар)#}
{#</aside>#}
<footer class="position-relative z-index-10 d-print-none">
      <!-- Main block - menus, subscribe form-->
      <div class="py-6 bg-gray-200 text-muted">
        <div class="container">
          <div class="row">
            <div class="col-lg-4 mb-5 mb-lg-0">
              <div class="font-weight-bold text-uppercase text-dark mb-3">Directory</div>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing.</p>
              <ul class="list-inline">
                <li class="list-inline-item"><a class="text-muted text-hover-primary" href="#" target="_blank" title="twitter"><i class="fab fa-twitter"></i></a></li>
                <li class="list-inline-item"><a class="text-muted text-hover-primary" href="#" target="_blank" title="facebook"><i class="fab fa-facebook"></i></a></li>
                <li class="list-inline-item"><a class="text-muted text-hover-primary" href="#" target="_blank" title="instagram"><i class="fab fa-instagram"></i></a></li>
                <li class="list-inline-item"><a class="text-muted text-hover-primary" href="#" target="_blank" title="pinterest"><i class="fab fa-pinterest"></i></a></li>
                <li class="list-inline-item"><a class="text-muted text-hover-primary" href="#" target="_blank" title="vimeo"><i class="fab fa-vimeo"></i></a></li>
              </ul>
            </div>
            <div class="col-lg-2 col-md-6 mb-5 mb-lg-0">
              <h6 class="text-uppercase text-dark mb-3">Rentals</h6>
              <ul class="list-unstyled">
                <li><a class="text-muted" href="index.html">Rooms     </a></li>
                <li><a class="text-muted" href="category-rooms.html">Map on top     </a></li>
                <li><a class="text-muted" href="category-2-rooms.html">Side map     </a></li>
                <li><a class="text-muted" href="category-3-rooms.html">No map     </a></li>
                <li><a class="text-muted" href="detail-rooms.html">Room detail     </a></li>
              </ul>
            </div>
            <div class="col-lg-2 col-md-6 mb-5 mb-lg-0">
              <h6 class="text-uppercase text-dark mb-3">Pages</h6>
              <ul class="list-unstyled">
                <li><a class="text-muted" href="compare.html">Comparison  <span class="badge badge-info-light ml-1">New</span>                                   </a></li>
                <li><a class="text-muted" href="team.html">Team  <span class="badge badge-info-light ml-1">New</span>                                   </a></li>
                <li><a class="text-muted" href="contact.html">Contact                                   </a></li>
                <li><a class="text-muted" href="pricing.html">Pricing                                   </a></li>
                <li><a class="text-muted" href="text.html">Text page                                   </a></li>
                <li><a class="text-muted" href="faq.html">F.A.Q.s                                   </a></li>
                <li><a class="text-muted" href="coming-soon.html">Coming soon                                   </a></li>
                <li><a class="text-muted" href="404.html">404 page  <span class="badge badge-info-light ml-1">New</span>                                   </a></li>
              </ul>
            </div>
            <div class="col-lg-4">
              <h6 class="text-uppercase text-dark mb-3">Daily Offers &amp; Discounts</h6>
              <p class="mb-3"> Lorem ipsum dolor sit amet, consectetur adipisicing elit. At itaque temporibus.</p>
              <form action="#" id="newsletter-form">
                <div class="input-group mb-3">
                  <input class="form-control bg-transparent border-dark border-right-0" type="email" placeholder="Your Email Address" aria-label="Your Email Address">
                  <div class="input-group-append">
                    <button class="btn btn-outline-dark border-left-0" type="submit"> <i class="fa fa-paper-plane text-lg"></i></button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      <!-- Copyright section of the footer-->
      <div class="py-1 font-weight-light bg-gray-100 text-gray-300">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-md-6 text-center text-md-left">
              <p class="text-sm mb-md-0">© 2020, Your company.  All rights reserved.</p>
            </div>
            <div class="col-md-6">
              <ul class="list-inline mb-0 mt-2 mt-md-0 text-center text-md-right">
                <li class="list-inline-item"><img class="w-2rem" src="https://d19m59y37dris4.cloudfront.net/directory/1-5/img/visa.svg" alt="..."></li>
                <li class="list-inline-item"><img class="w-2rem" src="https://d19m59y37dris4.cloudfront.net/directory/1-5/img/mastercard.svg" alt="..."></li>
                <li class="list-inline-item"><img class="w-2rem" src="https://d19m59y37dris4.cloudfront.net/directory/1-5/img/paypal.svg" alt="..."></li>
                <li class="list-inline-item"><img class="w-2rem" src="https://d19m59y37dris4.cloudfront.net/directory/1-5/img/western-union.svg" alt="..."></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </footer>
</body>
</html>